// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwbumcijzyshikbnixcw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3YnVtY2lqenlzaGlrYm5peGN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMDIxMTEsImV4cCI6MjA2MTU3ODExMX0.7ugvm8r_59yKEUg9-NfC-gcoafjzXqKQBle8bPc95rc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);